# Generated by Django 4.0.4 on 2022-05-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('expense', models.IntegerField(default=0)),
                ('sh_date', models.IntegerField(default=0)),
                ('owner_id', models.IntegerField()),
            ],
        ),
    ]
