# Generated by Django 4.0.4 on 2022-06-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense_ins_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense',
            field=models.IntegerField(verbose_name='Expense'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='sh_date',
            field=models.IntegerField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='shop_name',
            field=models.CharField(max_length=50, verbose_name='Shop Name'),
        ),
    ]
